name: masters-proj-eval
channels:
  - nvidia
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - cudnn=8
  - cython
  - pip
  - pip:
    - jupyter
    - flake8
    - autopep8
    - pandas==1.1.5
    - seaborn==0.11.1
    - imageio
    - tensorflow-addons==0.12.0
    - tensorflow==2.4.1
    - tensorflow-probability==0.12.2
    - tensorflow-datasets
    - image_similarity_measures
    - git+https://github.com/HedgehogCode/tensorflow-datasets-bw.git@0.7.0
    - git+https://github.com/HedgehogCode/deep-plug-and-play-prior